version: '3.8'
services:
  php:
    container_name: php
    build:
      context: .
      target: app_php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      test: [ "CMD", "docker-healthcheck" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '4000:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - php_socket:/var/run/php
    depends_on:
      - php
      - database

###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./var/pgsql:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  php_socket: